function [raw] = processRawTable(result,raw,varargin)
%PROCESSRAWTABLE takes raw and trimmed result table, compute phase difference
%with/without smoothing, and converts every signal to observer time.
%Encoder results are automatically upsampled to microphone Fs with linear
%interpolation
% result: results table generated by readFromList
% raw: raw signal table generated by readRawFromTDMS
% (optional) smoothing: T/F for a smoothing function over phase angle,
% could make the transition of delta phase look more straightforward

varargs = reshape(varargin,2,[]);
p = struct(varargs{:});

if isfield(p,"smoothing")
    applySmoothing = p.smoothing;
else
    applySmoothing = false;
end

%unwrap and load angle data
front = rad2deg(unwrap(deg2rad(result.("encoder data"){1}.front)));
rear = rad2deg(unwrap(deg2rad(result.("encoder data"){1}.rear)));

% make time array
fs_mic = single(result.("noise data"){1}.fs);
Fs_angle = height(front)/result.duration;
time_angle = 0:1/Fs_angle:result.duration;
time_angle = time_angle(1:end-1);

time_upsampled = 0:1/fs_mic:result.duration;
time_upsampled = time_upsampled(1:end-1);

if applySmoothing
% smooth original data (optional)
front = smooth(front,2^8);
rear = smooth(rear,2^8);
end

%upsample data to match
front_upsampled = interp1(time_angle,front,time_upsampled);
rear_upsampled = interp1(time_angle,rear,time_upsampled);

%wrap data back
front_upsampled = mod(front_upsampled,360);
rear_upsampled = mod(rear_upsampled,360);

Diff = front_upsampled-rear_upsampled;
Diff(Diff<0) = Diff(Diff<0)+360;
Diff(Diff>180) = Diff(Diff>180)-180;
frontPhase = front_upsampled;
frontPhase(frontPhase>180) = frontPhase(frontPhase>180)-180;
rearPhase = rear_upsampled;
rearPhase(rearPhase>180) = rearPhase(rearPhase>180)-180;
phaseInfo = table(time_upsampled',Diff',frontPhase',rearPhase',VariableNames=["time","diff","front","rear"]);

% Conversion to source time
Fs_mic = raw.fs;
time_mic = 0:1/Fs_mic:raw.duration;
time_mic = time_mic(1:end-1);

observerTimePressure = raw.("acoustic pressure"){1};

Tau = raw.r/343;
Tau_idx = round(Fs_mic*Tau,0);

time_mic = time_mic-Tau_idx*1/Fs_mic;

sourceTimePressure = table(time_mic',observerTimePressure,VariableNames=["time","Pressure"]);
toAppend = cell2table({phaseInfo,sourceTimePressure},VariableNames=["phaseInfo","sourceTimePressure"]);
raw = [raw,toAppend];

end

